<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DLMS_DAL\DLMS_DAL.csproj" />
    <ProjectReference Include="..\DLMS_MODELS\DLMS_MODELS.csproj" />
  </ItemGroup>

</Project>
