<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Gurux.Common" Version="8.4.2302.901" />
    <PackageReference Include="Gurux.DLMS" Version="9.0.2311.601" />
    <PackageReference Include="Gurux.Net" Version="8.4.2302.904" />
    <PackageReference Include="Gurux.Serial" Version="8.4.2302.902" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DLMS_SERVICE\DLMS_SERVICE.csproj" />
    <ProjectReference Include="..\DLMS_COMMUNICATION\DLMS_COMMUNICATION.csproj" />
    <ProjectReference Include="..\DLMS_DAL\DLMS_DAL.csproj" />
    <ProjectReference Include="..\DLMS_MODELS\DLMS_MODELS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="asc_connection">
      <HintPath>..\DLMS_SERVICE\bin\Debug\net8.0\asc_connection.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
